name: CI

on:
    push:
        branches: [ master ]

jobs:
    deploy:
        runs-on: self-hosted
    
        strategy:
            matrix:
                node-version: [12.x]
            
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with: 
                    node-version: ${{ matrix.node-version }}
            - run: npm install
            - run: npm run build --if-present
            - run: cp -a ${{github.workspace}}/dist/. ~/portfolio/
            - run: pm2 kill
            - run: pm2 start ${{github.workspace}}/dist/server.bundle.js --name portfolio
